.\" $Header: /home/terpstra/cvt/lurker/lurker/index/lurker-list.1,v 1.5 2004-08-24 16:06:30 terpstra Exp $
.\"
.\"	transcript compatibility for postscript use.
.\"
.\"	synopsis:  .P! <file.ps>
.\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
'\" t 
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n  
.TH "LURKER\-LIST" "1" 
.SH "NAME" 
lurker\-list \(em parses lists from the config file 
.SH "SYNOPSIS" 
.PP 
\fBlurker\-list\fR [\-c <config-file>]  [\-i \-g \-t \-a \-l \-d \-s \-o]  [listid ...]  
.SH "DESCRIPTION" 
.PP 
\fBlurker\-list\fR outputs various lurker settings 
from the config file for use in shell scripts.  Do not use sed/grep/etc, 
instead use this as it respects include. 
.PP 
If no list ids are given, then all lists are dumped. If no field 
is specified, then all fields are dumped. 
.SH "OPTIONS" 
.IP "\fB\-c config-file\fP" 10 
Use this config file for lurker settings. 
.IP "\fB\-i\fP" 10 
Output only the list id 
.IP "\fB\-g\fP" 10 
Output only the group 
.IP "\fB\-t\fP" 10 
Output only the title 
.IP "\fB\-a\fP" 10 
Output only the email address 
.IP "\fB\-l\fP" 10 
Output only the url link 
.IP "\fB\-d\fP" 10 
Output only the description 
.IP "\fB\-s\fP" 10 
Output only the language 
.IP "\fB\-o\fP" 10 
Output only the offline status 
.SH "SEE ALSO" 
.PP 
lurker\-index(1), lurker\-prune(1), lurker\-params(1), lurker\-search(1) 
.PP 
lurker documentation on http://lurker.sourceforge.net/ 
.SH "COPYRIGHT" 
.PP 
Copyright (C) 2002: Wesley W. Terpstra <terpstra@users.sourceforge.net> 
 
.PP 
This program is free software; you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by 
the Free Software Foundation; version 2. 
 
.PP 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU General Public License for more details. 
 
.PP 
You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software 
Foundation, Inc., 59 Temple Place - Suite 330, 
Boston, MA 02111-1307, USA. 
 
.SH "BUGS" 
.PP 
Before reporting a bug, please confirm that the bug you found is 
still present in the latest official release. If the problem persists, 
then send mail with instructions describing how to reproduce the bug to 
<lurker\-users@lists.sourceforge.net>. 
.\" created by instant / docbook-to-man, Mon 23 Aug 2004, 18:11 
