.\" $Header: /home/terpstra/cvt/lurker/lurker/index/lurker-params.1,v 1.7 2004-08-27 15:04:05 terpstra Exp $
.\"
.\"	transcript compatibility for postscript use.
.\"
.\"	synopsis:  .P! <file.ps>
.\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
'\" t 
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n  
.TH "LURKER\-PARAMS" "1" 
.SH "NAME" 
lurker\-params \(em parses parameters from the config file 
.SH "SYNOPSIS" 
.PP 
\fBlurker\-params\fR [\-c <config-file>]  [\-f <locale>]  [\-d \-a \-n \-e \-x \-m \-i \-w \-h \-r]  
.SH "DESCRIPTION" 
.PP 
\fBlurker\-params\fR outputs various lurker settings 
from the config file for use in shell scripts.  Do not use sed/grep/etc, 
instead use this as it respects include.   
.SH "OPTIONS" 
.IP "\fB\-c config-file\fP" 10 
Use this config file for lurker settings. 
.IP "\fB\-f locale\fP" 10 
Choose lurker config fields from the specified locale 
(it defaults to selecting the fallback case for each field). 
.IP "\fB\-d\fP" 10 
Output only the dbdir parameter 
.IP "\fB\-a\fP" 10 
Output only the archive parameter 
.IP "\fB\-n\fP" 10 
Output only the administrator name 
.IP "\fB\-e\fP" 10 
Output only the administrator email address 
.IP "\fB\-x\fP" 10 
Output only the xslt processing command 
.IP "\fB\-m\fP" 10 
Output only the mime pgp verifying command 
.IP "\fB\-i\fP" 10 
Output only the inline pgp verifying command 
.IP "\fB\-w\fP" 10 
Output only the web_cache state 
.IP "\fB\-h\fP" 10 
Output only the hide_email state 
.IP "\fB\-r\fP" 10 
Output only the raw_email state 
.SH "SEE ALSO" 
.PP 
lurker\-index(1), lurker\-prune(1), lurker\-list(1), lurker\-search(1) 
.PP 
lurker documentation on http://lurker.sourceforge.net/ 
.SH "COPYRIGHT" 
.PP 
Copyright (C) 2002: Wesley W. Terpstra <terpstra@users.sourceforge.net> 
 
.PP 
This program is free software; you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by 
the Free Software Foundation; version 2. 
 
.PP 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU General Public License for more details. 
 
.PP 
You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software 
Foundation, Inc., 59 Temple Place - Suite 330, 
Boston, MA 02111-1307, USA. 
 
.SH "BUGS" 
.PP 
Before reporting a bug, please confirm that the bug you found is 
still present in the latest official release. If the problem persists, 
then send mail with instructions describing how to reproduce the bug to 
<lurker\-users@lists.sourceforge.net>. 
.\" created by instant / docbook-to-man, Fri 27 Aug 2004, 16:53 
