.TH "LURKER\-REGENERATE" "1" 
.SH "NAME" 
lurker\-regenerate \(em imports messages into the archive 
.SH "SYNOPSIS" 
.PP 
\fBlurker\-regenerate\fR [<bin-dir>]  [<config-file>]  
.SH "DESCRIPTION" 
.PP 
\fBlurker\-regenerate\fR regenerates obsolete 
lurker databases created by lurker >= 0.6. It generates 
a new database first, then removes the old one. You will 
need enough space for 2 times your obsolete database. 
The two arguments are optional. 
.SH "OPTIONS" 
.IP "\fBbin-dir\fP" 10 
The directory containing lurker-{index,list,params,prune}. 
This defaults to where 'make install' placed them. 
.IP "\fBconfig-file\fP" 10 
The config-file for which lurker-regenerate rebuilds the  
database. 
.SH "SEE ALSO" 
.PP 
lurker documentation on http://lurker.sourceforge.net/ and in 
/usr/share/doc/lurker. 
.SH "AUTHOR" 
.PP 
This manual page was written by Jonas Meurer <jonas@freesources.org> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU Free Documentation 
License, Version 1.1 or any later version published by the Free 
Software Foundation; with no Invariant Sections, no Front-Cover 
Texts and no Back-Cover Texts. 
.\" created by instant / docbook-to-man, Sun 26 Feb 2006, 14:46 
