.\" $Header: /home/terpstra/cvt/lurker/lurker/index/lurker-index.1,v 1.10 2004-08-25 21:40:10 terpstra Exp $
.\"
.\"	transcript compatibility for postscript use.
.\"
.\"	synopsis:  .P! <file.ps>
.\"
.de P!
.fl
\!!1 setgray
.fl
\\&.\"
.fl
\!!0 setgray
.fl			\" force out current output buffer
\!!save /psv exch def currentpoint translate 0 0 moveto
\!!/showpage{}def
.fl			\" prolog
.sy sed -e 's/^/!/' \\$1\" bring in postscript file
\!!psv restore
.
.de pF
.ie     \\*(f1 .ds f1 \\n(.f
.el .ie \\*(f2 .ds f2 \\n(.f
.el .ie \\*(f3 .ds f3 \\n(.f
.el .ie \\*(f4 .ds f4 \\n(.f
.el .tm ? font overflow
.ft \\$1
..
.de fP
.ie     !\\*(f4 \{\
.	ft \\*(f4
.	ds f4\"
'	br \}
.el .ie !\\*(f3 \{\
.	ft \\*(f3
.	ds f3\"
'	br \}
.el .ie !\\*(f2 \{\
.	ft \\*(f2
.	ds f2\"
'	br \}
.el .ie !\\*(f1 \{\
.	ft \\*(f1
.	ds f1\"
'	br \}
.el .tm ? font underflow
..
.ds f1\"
.ds f2\"
.ds f3\"
.ds f4\"
'\" t 
.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n  
.TH "LURKER\-INDEX" "1" 
.SH "NAME" 
lurker\-index \(em imports messages into the archive 
.SH "SYNOPSIS" 
.PP 
\fBlurker\-index\fR [\-c <config-file>]  [\-l <list>]  [\-i <mbox/maildir>]  [\-v \-d \-n \-u \-f]  [\-m | \-b <count>]  
.SH "DESCRIPTION" 
.PP 
\fBlurker\-index\fR indexes messages from 
standard input and stores them in the lurker database. 
It imports either a single message, or a batch of messages 
in mbox format.  
.SH "OPTIONS" 
.IP "\fB\-c config-file\fP" 10 
Use this config file for lurker settings. 
.IP "\fB\-l listid\fP" 10 
Import messages to the named mailing list. This should match 
the value in the lurker.conf after the 'list = ' entry. 
.IP "\fB\-b count\fP" 10 
Import a batch of messages; flush every count messages. A 
good value for count is 5. The larger this parameter, the more CPU 
power lurker needs during import, but the less disk seeks. 
.IP "" 10 
It is important to note that lurker reads files from a 
maildirs and mailboxes in order and may miss new messages 
delivered during the import. For this reason, setting up lurker to 
be invoked properly when new mail is delivered is essential. Only 
use lurker\-index with '\-b' when importing from non-active mail 
folders. 
.IP "" 10 
By default, lurker\-index reads from standard input in mbox 
format, delimited by 'From <addr> <date>' lines.  
Be aware that if the mbox is not delimited correctly between 
messages it will be interpretted as a single message with an 
invalid date. To read other sources, see the '\-i' option. 
.IP "\fB\-m\fP" 10 
Import a single message. In this mode lurker will never 
interpret 'From ' lines as message delimiters. When being fed 
newly delivered mail, this is the preferred mode of operation.  
Try to turn off the 'From ' escaping of your MTA when using  
this mode as lurker does it's own escaping which is generally 
smarter. 
.IP "" 10 
This option should be used when lurker\-index is invoked by 
the MTA for newly delivered email. For importing batches of 
archived mail, see the '\-b' option. 
.IP "\fB\-i mbox/maildir\fP" 10 
Import messages from the specified mailbox or maildir. 
When '\-b' is specified, lurker\-index by default reads a mailbox 
(mbox format) from standard input. If the '\-i' parameter is a file, 
the file is assumed to be in the mbox format and is read instead 
of standard input.  If the parameter is a directory, the directory 
is assumed to be in maildir format. 
.IP "" 10 
If '\-m' is used, the input MUST be a raw email, 
preferably with a mbox header, never a maildir. 
.IP "\fB\-v\fP" 10 
Verbose operation. Lurker will output statistics about import 
speed to assist you in tweaking options for best throughput on 
your system. It also helps you know how much longer you will have 
to wait. 
.IP "\fB\-d\fP" 10 
Drop duplicates per list. This option will check the 
database to see if the message has already been imported to a 
mailing list. Only if it has not been imported will lurker append 
it to the mailbox. Even without this option lurker does not index 
a message twice. If an import failed part-way through, you 
probably want this option to avoid needless replication. However, 
to generate mailboxes which accurately reflect delivery, leave the 
option off. 
.IP "\fB\-n\fP" 10 
Don't compress messages. This will increase the database 
size and import speed. Lurker can handle a database with mixed 
compressed and uncompressed messages. However, zcat/gzip and 
database upgrades cannot. If you need these to function, you 
should never mix compressed and uncompressed messages within a 
single mailing list. 
.IP "\fB\-u\fP" 10 
Trust user Date headers from the email more than the delivery  
time. Normally lurker compares the two and if the user time differs 
too much from the delivery time, the delivery time is used instead. 
When this option is used, lurker will simply trust the user Date 
header whenever it exists, otherwise it uses the delivery time. 
.IP "" 10 
This option should never be used as a default. It is intended 
for dealing with corrupt mailboxes or maildirs. A better solution 
than using this option is to find an uncorrupted copy of the mail. 
 
.IP "\fB\-f\fP" 10 
Fast import (but vulnerable to power-failure). This may 
improve the lifetime of your hard-disk and increase import speed 
by up to 30%. However, if the power fails during import or shortly 
thereafter, it is possible you will have a corrupted database. If 
you use a journaling filesystem, lurker guarantees no corruption 
when you OMIT this parameter. 
.SH "SEE ALSO" 
.PP 
lurker\-prune(1), lurker\-params(1), lurker\-list(1), lurker\-search(1) 
.PP 
lurker documentation on http://lurker.sourceforge.net/ 
.SH "COPYRIGHT" 
.PP 
Copyright (C) 2002: Wesley W. Terpstra <terpstra@users.sourceforge.net> 
 
.PP 
This program is free software; you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by 
the Free Software Foundation; version 2. 
 
.PP 
This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU General Public License for more details. 
 
.PP 
You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software 
Foundation, Inc., 59 Temple Place - Suite 330, 
Boston, MA 02111-1307, USA. 
 
.SH "BUGS" 
.PP 
Before reporting a bug, please confirm that the bug you found is 
still present in the latest official release. If the problem persists, 
then send mail with instructions describing how to reproduce the bug to 
<lurker\-users@lists.sourceforge.net>. 
.\" created by instant / docbook-to-man, Wed 25 Aug 2004, 23:39 
