#! /bin/sh -e
# Expects: (path to lurker-index / lurker-params) (cfg)
# Both are optional

epath="$1"
cfg="$2"

if ! test -z "$epath"; then $epath="$epath/"; fi
if ! test -z "$cfg"; then copt="-c"; fi

dbdir=`${epath}lurker-params $copt "$cfg" -d`
cd "$dbdir"

if test -d .tmp; then \
	echo The database appears to already have/is being converted.
	echo Please deal with the '.tmp' folder in the $dbdir and try again
	exit 1
fi

mkdir .tmp
cd .tmp
mv -i ../* .

for l in `${epath}lurker-list $copt "$cfg" -i`; do
  echo Reindexing $l
  gzip -dfc < $l | ${epath}lurker-index $copt "$cfg" -p ./db -l $l -v
done

cd ..
rm -rf .tmp
